# https://taskfile.dev

version: '3'

vars:
  INPUT_DIR: ../../data/

silent: true

tasks:
  run:
    preconditions: 
    - sh: "[[ ! -z {{.CLI_ARGS}} ]] "
      msg: Please provide the dir of the day as cli arg (task create -- "PATH")
    - sh: test -f "{{.CLI_ARGS}}/main.go"
      msg: "Please provide a path to a dir with a main.go as cli arg"
    cmds:
      - go run {{.CLI_ARGS}}/main.go {{.INPUT_DIR}}{{.CLI_ARGS}}.txt
  
  create:
    preconditions: 
    - sh: "[[ ! -z {{.CLI_ARGS}} ]] "
      msg: Please provide the the day as cli arg (task create -- "DAY")
    cmds:
      - mkdir day{{.CLI_ARGS}}
      - |
        cd day{{.CLI_ARGS}}
        go mod init main
        touch main.go
        touch {{.CLI_ARGS}}.go
        touch {{.CLI_ARGS}}_test.go
